# Generated by Django 5.1.3 on 2024-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
    ]
