# Generated by Django 5.1.3 on 2024-11-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_docs_surgitec', '0002_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='pdf_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
