# Generated by Django 5.1.3 on 2024-11-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_docs_surgitec', '0003_funcionario_pdf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='pdf_id',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='view_docs_surgitec.funcionario'),
        ),
    ]
